albuns/urls.py
from django.urls import path

from . import views

app_name = 'albuns'
urlpatterns = [
    path('', views.AlbumListView.as_view(), name='index'),
    path('create/', views.create_album, name='create'),
    path('<int:album_id>/', views.detail_album,
         name='detail'),
    path('update/<int:album_id>/', views.update_album, name='update'),
    path('delete/<int:album_id>/', views.delete_album, name='delete'),
    path('<int:album_id>/review/', views.create_review, name='review'),
    path('lists/', views.ListListView.as_view(), name='lists'),
]

entrega2/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('staticpages.urls')),
    path('albuns/', include('albuns.urls')),  # adicionar esta linha
    path('admin/', admin.site.urls),
]

staticpages/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("about/", views.about, name="about"),  # adicione esta linha
    path("", views.index, name="index"),
]

albuns/models.py
from django.db import models
from django.conf import settings


class Album(models.Model):
    name = models.CharField(max_length=255)
    release_year = models.IntegerField()
    poster_url = models.URLField(max_length=200, null=True)
    post_date = models.DateTimeField(auto_now=True)
    info = models.CharField(max_length=255000)

    def __str__(self):
        return f'{self.name} ({self.release_year})'


class Review(models.Model):
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )
    post_date = models.DateTimeField(auto_now=True)
    text = models.CharField(max_length=255)
    album = models.ForeignKey(Album, on_delete=models.CASCADE)

    def __str__(self):
        return f'"{self.text}" - {self.author.username}'


class List(models.Model):
    name = models.CharField(max_length=255)
    desc = models.CharField(max_length=255)
    albuns = models.ManyToManyField(Album)

    def __str__(self):
        return f'{self.name}'

staticpages/models.py
from django.db import models

# Create your models here.

albuns/forms.py
from django.forms import ModelForm
from .models import Album, Review


class AlbumForm(ModelForm):
    class Meta:
        model = Album
        fields = [
            'name',
            'release_year',
            'poster_url',
            'info',
        ]
        labels = {
            'name': 'Título',
            'release_year': 'Ano de Lançamento',
            'poster_url': 'URL do poster',
            'info': 'Informações do Álbum'
        }


class ReviewForm(ModelForm):
    class Meta:
        model = Review
        fields = [
            'author',
            'text',
        ]
        labels = {
            'author': 'Usuário',
            'text': 'Comentário',
        }

albuns/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse, reverse_lazy
from django.views import generic

from .forms import AlbumForm, ReviewForm
from .models import List, Album, Review


def detail_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    context = {'album': album}
    return render(request, 'albuns/detail.html', context)


class AlbumListView(generic.ListView):
    model = Album
    template_name = 'albuns/index.html'


def create_album(request):
    if request.method == 'POST':
        album_form = AlbumForm(request.POST)
    else:
        album_form = AlbumForm()
    context = {'album_form': album_form, }
    return render(request, 'albuns/create.html', context)


def update_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)

    if request.method == "POST":
        form = AlbumForm(request.POST)
        if form.is_valid():
            album.name = form.cleaned_data['name']
            album.release_year = form.cleaned_data['release_year']
            album.poster_url = form.cleaned_data['poster_url']
            album.save()
            return HttpResponseRedirect(
                reverse('albuns:detail', args=(album.id, )))
    else:
        form = AlbumForm(
            initial={
                'name': album.name,
                'release_year': album.release_year,
                'poster_url': album.poster_url
            })

    context = {'album': album, 'form': form}
    return render(request, 'albuns/update.html', context)


def delete_album(request, album_id):
    album = get_object_or_404(Album, pk=album_id)

    if request.method == "POST":
        album.delete()
        return HttpResponseRedirect(reverse('albuns:index'))

    context = {'album': album}
    return render(request, 'albuns/delete.html', context)


def create_review(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            review_author = form.cleaned_data['author']
            review_text = form.cleaned_data['text']
            review = Review(author=review_author,
                            text=review_text,
                            album=album)
            review.save()
            return HttpResponseRedirect(
                reverse('albuns:detail', args=(album_id, )))
    else:
        form = ReviewForm()
    context = {'form': form, 'album': album}
    return render(request, 'albuns/review.html', context)


class ListListView(generic.ListView):
    model = List
    template_name = 'albuns/lists.html'

staticpages/views.py
from django.http import HttpResponse
from django.shortcuts import render


def index(request):
    context = {}
    return render(request, "staticpages/index.html", context)


def about(request):
    context = {}
    return render(request, "staticpages/about.html", context)

albuns/templates/albuns/create.html
{% extends 'base.html' %}

{% block title %}
Criar Álbum
{% endblock title %}

{% block content %}
<h2>Adicionar Álbum</h2>

<form action="{% url 'albuns:create' %}" method="post">
    {% csrf_token %}
    {{ album_form.as_p }}
    <button type="submit">Criar</button>
</form>

{% endblock content %}

albuns/templates/albuns/delete.html
{% extends 'base.html' %}

{% block content %}
<form action="{% url 'albuns:delete' album.id %}" method="post">
    {% csrf_token %}
    <p>
        Você tem certeza que deseja apagar o álbum "{{ album.name }} ({{ album.release_year }})"?
    </p>
    <button type="submit">Apagar</button>
</form>

{% endblock content %}

albuns/templates/albuns/detail.html
{% extends 'base.html' %}

{% block title %}
{{ album.name }} ({{ album.release_year }}
{% endblock title %}

{% block content %}
<h2>Detalhes do Álbum {{ album.name }} ({{ album.release_year }}) — {{ album.post_date|date:"D d M Y"}}</h2>

<hr>

<section class="dados-de-album">
    <img src="{{ album.poster_url }}" alt="poster do album {{ album.name}}">
    <ul>
        <li>Nome: {{ album.name }}</li>
        <li>Ano de Lançamento: {{ album.release_year }} </li>
        <li>Data de Postagem: {{album.post_date }} </li>
        <li>Categorias: {% for list in album.list_set.all reversed %} <a href="{% url 'albuns:lists' %}">{{list.name}}
            </a> {% endfor %}</li>
        <li>Informação: {{album.info }}</li>
        <li><a href="{% url 'albuns:review' album.id %}">Comentar</a></li>
        <li><a href="{% url 'albuns:update' album.id %}">Editar</a></li>
        <li><a href="{% url 'albuns:delete' album.id %}">Apagar</a></li>
    </ul>
</section>

<hr>

<section>
    <header>
        <h3>Comentários</h3>
    </header>
    <ul>
        {% if album.review_set.all %}
        {% for review in album.review_set.all reversed %}
        <figure>
            <blockquote>
                "{{ review.text }}"
            </blockquote>
            <figcaption>—{{ review.author }} | {{ review.post_date|date:"D d M Y" }} {{ review.post_date|time:"H:i" }}
        </figure>
        {% endfor %}
        {% else %}
        <p>Ainda não existe nenhum comentário para este filme.</p>
        {% endif %}
    </ul>

    <hr>

    <a href="{% url 'albuns:review' album.pk %}"><button>Adicione um Comentario</button></a>
</section>
{% endblock content %}

albuns/templates/albuns/index.html
{% extends 'base.html' %}

{% block content %}
<h2>Todos os Álbuns</h2>
<section>
    <p>Não encontrou o álbum? <a href="{% url 'albuns:create' %}">Adicionar Novo Álbum</a></p>
</section>
{% if album_list %}
<section class="lista-de-cards">
    {% for album in album_list %}
    <article class="card">
        <a href="{% url 'albuns:detail' album.id %}"><img src="{{ album.poster_url }}"
                alt="poster do album {{ album.name}}"></a> <!-- modifique esta linha -->
        <p>{{ album.name }} ({{ album.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum album.</p>
{% endif %}

{% endblock content %}

albuns/templates/albuns/lists.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock title %}

{% block content %}
<h2>Categorias</h2>

<section>
    {% for list in list_list %}
    <hr>
    <article>
        <header>
            <h2>{{list.name}} </h2>
        </header>
        <div>
            <h3>{{list.desc}}</h3>
        </div>
        <div class="lista-de-cards">
            {% for album in list.albuns.all %}
            <div class="card">
                <a href="{% url 'albuns:detail' album.id %}"><img src="{{ album.poster_url }}"
                        alt="poster do álbum {{ album.name}}"></a>
                <p>{{ album.name }} ({{ album.release_year }})</p>
            </div>
            {% endfor %}
        </div>
    </article>
    {% endfor %}
</section>

{% endblock content %}

albuns/templates/albuns/review.html
{% extends 'base.html' %}

{% block content %}
<h2>Comentar sobre o Álbum {{ album.name }} ({{ album.release_year }})</h2>

<form action="{% url 'albuns:review' album.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Comentar</button>
</form>

<p><a href="{% url 'albuns:detail' album.id %}">Voltar para a página do álbum</a></p>
{% endblock content %}

albuns/templates/albuns/search.html
{% extends 'base.html' %}

{% block content %}
<h2>Busca de Álbuns por Nome</h2>
<form action="{% url 'albuns:search' %}">
    <p>
        <label for="id_query">Título:</label>
        <input type="text" name="query" id="id_query" />
    </p>
    <button type="submit">Buscar</button>
</form>


<h2>Resultado da Busca</h2>
{% if album_list %}
<section class="lista-de-cards">
    {% for album in album_list %}
    <article class="card">
        <img src="{{ album.poster_url }}" alt="poster do álbum {{ album.name}}">
        <p>{{ album.name }} ({{ album.release_year }})</p>
    </article>
    {% endfor %}
</section>
{% else %}
<p>Não foi encontrado nenhum álbum para a busca.</p>
{% endif %}

{% endblock content %}

albuns/templates/albuns/update.html
{% extends 'base.html' %}

{% block content %}
<h2>Atualizar Dados do Álbum {{ album.name }}({{ album.release_year}})</h2>
<form method="POST" action="{% url 'albuns:update' album.id%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Atualizar</button>
</form>

{% endblock content %}

staticpages/templates/staticpages/about.html
{% extends 'base.html' %}

{% block title %}
Sobre
{% endblock title %}

{% block content %}
<h2>Sobre este site</h2>
{% endblock content %}

staticpages/templates/staticpages/index.html
{% extends 'base.html' %}

{% block title %}
Página Inicial
{% endblock title %}

{% block content %}
<h1><i>Meus Álbuns!</i></h1>
<p>A Página que contém meus álbuns e informações sobre eles</p>
{% endblock content %}

templates/base.html
{% load static %}
<!-- adicione esta linha -->

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>
        {% block title %}{% endblock %} | Watch that film!
    </title>
    <link href="https://fonts.googleapis.com/css?family=Inter&display=swap" rel="stylesheet" />
    <!-- adicione esta linha -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> <!-- adicione esta linha -->
</head>

<body>
    <header id="cabecalho-principal">
        <a href="{% url 'index' %}"> <img src="{% static 'logoPoli.png' %}" width=150></a>
        <a href="{% url 'index' %}">
            <h1>Meus Álbuns</h1>
        </a>
        <nav id="navegacao-principal">
            <ul>
                <li><a href="{% url 'albuns:index' %}">Álbuns</a></li>
                <li><a href="{% url 'albuns:lists' %}">Categorias</a></li> <!-- adicionar esta linha -->
                <li><a href="{% url 'about' %}">Sobre</a></li>
            </ul>
        </nav>
    </header>
    <main id="conteiner-principal">
        {% block content %}
        {% endblock content %}
    </main>
    <footer id="rodape-principal">
        <p>
            <small>Copyright 2021</small>
        </p>
    </footer>
</body>

</html>